stages:
  - checks
  - tests

cache:
  paths:
  - node_modules

variables:
    GIT_SUBMODULE_STRATEGY: normal
    CI_DEBUG_TRACE: "true"

before_script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8

check_python_style:
  stage: checks
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  artifacts:
    when: on_failure
    paths:
      - flake8_output.txt
    expire_in: 1 week
  before_script:
    - python3 -m pip install flake8
  script:
    - python3 -m flake8 --config=.flake8 --output-file=flake8_output.txt --tee


tests_unit:
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  stage: tests
  tags:
    - gdb_amd64_test
  artifacts:
    paths:
    - /tests/*.log
    - tests/results/*
    reports:
      junit:
        - tests/results/*
    when: always
    expire_in: 1 week
  script:
    - python3 -m pip install -r requirements.txt
    - cd $CI_PROJECT_DIR/tests
    - python3 ./run_tests.py
